spring:
  application:
    name: webflux-course
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@webfluxcoursecluster.btetjbw.mongodb.net/{DB_NAME:webflux-course}?retryWrites=true&w=majority
      auto-index-creation: true


